// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Error": {
    "description": "<p>We've unfortunately encountered an error.</p><p>You can try to <retry>reload the page</retry> you were visiting.</p>",
    "title": "Something went wrong!"
  },
  "IndexPage": {
    "description": "This is a basic example that demonstrates the usage of <code>next-intl</code> with the Next.js App Router. Try changing the locale in the top right corner and see how the content changes.",
    "title": "Clear cutoff"
  },
  "LocaleLayout": {
    "title": "Clear cutoff",
    "description": "This is a basic example that demonstrates the usage of <code>next-intl</code> with the Next.js App Router. Try changing the locale in the top right corner and see how the content changes."
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, tr {TR Deutsch} en {🇺🇸 English} other {Unknown}}"
  },
  "Manifest": {
    "name": "Clear cutoff"
  },
  "Navigation": {
    "home": "Home",
    "pathnames": "Pathnames"
  },
  "NotFoundPage": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "PageLayout": {
    "links": {
      "docs": {
        "description": "Learn more about next-intl in the official docs.",
        "href": "https://next-intl.dev",
        "title": "Docs"
      },
      "source": {
        "description": "Browse the source code of this example on GitHub.",
        "href": "https://github.com/amannn/next-intl/tree/main/examples/example-app-router",
        "title": "Source code"
      }
    }
  },
  "PathnamesPage": {
    "description": "<p>The pathnames are internationalized too.</p><p>If you're using the default language English, you'll see <code>/en/pathnames</code> in the browser address bar on this page.</p><p>If you change the locale to German, the URL is localized accordingly (<code>/de/pfadnamen</code>).</p>",
    "title": "Pathnames"
  },
  "CourseHeader": {
    "title": "Clear {courseName} exam with us!",
    "description": "Don't miss out on this incredible opportunity to advance your skills at an unbeatable price.",
    "trialText": "3 day FREE trial",
    "ratingsbyourstudents": "Average ratings by our students"
  },
  "Buttons": {
    "login": "Login",
    "register": "Start for FREE",
    "logout": "Logout"
  },
  "carousel": {
    "text": "Preparing for other exams? Check All Teaching Exams by Clear Cutoff!",
    "highlight": "All Teaching Exams",
    "button": {
      "text": "View all Courses & Test Series!"
    }
  },
  "PricingSection": {
    "eyebrow": "Simple. Transparent. Affordable.",
    "title": "One Price, Everything Included!",
    "description": "One-time payment. 1-year access. Everything you need to pass on your first attempt.",
    "tailContent": {
      "title": "Used by 10,000+ students to clear {courseName} exams.",
      "description": "Join thousands of successful {courseName} aspirants who chose smart, affordable learning over expensive coaching!",
      "rating": {
        "rat": "4.9+",
        "text": "Average Rating by our Students!"
      }
    }
  }
};
export default messages;